
export const GET_LOGIN = "GET_LOGIN";
export const SET_LOGIN = "SET_LOGIN";
export const SET_LOADING_LOGIN = "SET_LOGIN_LOADING";
export const STORE_USER_DATAS = "SORE_USER_DATAS";
export const UPDATE_USER_DATAS = "UPDATE_USER_DATAS";

export const SET_MENU_ACTIVE = "SET_MENU_ACTIVE";

export const GET_MESIN_DATAS = "GET_MESIN_DATAS";
export const STORE_MESIN_DATAS = "STORE_MESIN_DATAS";

export const CREATE_LAYANAN = "CREATE_LAYANAN";
export const GET_LAYANAN = "GET_LAYANAN";
export const STORE_LAYANAN = "STORE_LAYANAN";
export const GET_LAYANAN_BY_ID = "GET_LAYANAN_BY_ID";
export const STORE_LAYANAN_DETAIL = "STORE_LAYANAN_DETAIL";
export const DELETE_LAYANAN = "DELETE_LAYANAN";
export const UPDATE_LAYANAN = "UPDATE_LAYANAN";

export const CREATE_PETUGAS = "CREATE_PETUGAS";
export const GET_PETUGAS = "GET_PETUGAS";
export const STORE_PETUGAS = "STORE_PETUGAS";
export const GET_PETUGAS_BY_ID = "GET_PETUGAS_BY_ID";
export const STORE_PETUGAS_DETAIL = "STORE_PETUGAS_DETAIL";
export const DELETE_PETUGAS = "DELETE_PETUGAS";
export const UPDATE_PETUGAS = "UPDATE_PETUGAS";

export const SET_LOADING_API_CALL = "SET_LOADING_API_CALL";
export const SET_UPDATE_DATA = "SET_UPDATE_DATA";
export const SET_DETAIL = "SET_DETAIL";
export const STORE_DETAIL = "STORE_DETAIL";


export const CREATE_MACHINE = "CREATE_MACHINE";
export const GET_MACHINE = "GET_MACHINE";
export const STORE_MACHINE_SETTING = "STORE_MACHINE_SETTING";
export const UPDATE_MACHINE = "UPDATE_MACHINE";
